config/routes.rb
Rails.application.routes.draw do
  get 'anagrams/check'
  root 'pages#home'
  
  get 'palindrome/check', to: 'palindrome#check'
  
  get 'rock_paper_scissors/check', to: 'rock_paper_scissors#check'
  
  get 'anagrams/check', to: 'anagrams#check'
  
  resources :desserts, only: [:index] do
    collection do
      post 'check'
    end
  end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/concerns/dessert.rb
class Dessert
  attr_accessor :name, :calories

  def initialize(name, calories)
    @name = name
    @calories = calories
  end

  def healthy?
    @calories < 200
  end

  def delicious?
    true
  end

end

app/models/concerns/jelly_bean.rb
class JellyBean < Dessert
  
  attr_accessor :flavor

  def initialize(name, calories, flavor)
    super(name, calories)
    @flavor = flavor
  end

  def delicious?
    @flavor.downcase != "black licorice"
  end
end

app/controllers/anagrams_controller.rb
class AnagramsController < ApplicationController
  def check
    @words = params[:words]&.split(',')&.map(&:strip) || []
    @result = combine_anagrams(@words) if @words.any?
  end

  private

  def combine_anagrams(words)
    # Group words by their sorted lowercase letters
    words.group_by { |word| word.downcase.chars.sort.join }
         .values
         .select { |group| group.length > 1 }  # Only return groups with more than one word
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/desserts_controller.rb
class DessertsController < ApplicationController
  def index
    #Create some exemples desserts
    @dessert = Dessert.new("Ice Cream", 200)
    @healthy_dessert = Dessert.new("Fruit", 100)
    @jelly_bean = JellyBean.new("Jelly Bean", 100, "Cherry")
    @black_licorice = JellyBean.new("Black Licorice", 200, "Black Licorice")
  end

  def check
    name = params[:name]
    calories = params[:calories].to_i
    flavor = params[:flavor]

    if flavor.present?
      @dessert = JellyBean.new(name, calories, flavor)
    else
      @dessert = Dessert.new(name, calories)
    end

    render :result

  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/palindrome_controller.rb
class PalindromeController < ApplicationController
  def check
    @input = params[:input]
    @result = palindrome?(@input)
  end

  private

  def palindrome?(str)
    return false if str.nil?
    cleaned_str = str.gsub(/\W/, '').downcase
    cleaned_str == cleaned_str.reverse
  end

end

app/controllers/rock_paper_scissors_controller.rb
class RockPaperScissorsController < ApplicationController
  def check
    @input = params.fetch(:input, {}).permit!.to_h.values.map { |player| [player[:name], player[:strategy]] } || []
    if @input.length == 2
      @result = rps_game_winner(@input)
    else
      @result = "Error: Wrong number of players"
    end
  end

  private

  def rps_game_winner(game)
    raise WrongNumberOfPlayersError if game.nil? || game.length != 2

    valid_strategies = ['R', 'P', 'S']

    player1, player2 = game

    player1_name, player1_strategy = player1
    player2_name, player2_strategy = player2

    unless player1_strategy && player2_strategy && valid_strategies.include?(player1_strategy.upcase) && valid_strategies.include?(player2_strategy.upcase)
      raise NoSuchStrategyError, "Strategy must be one of R, P, S"
    end

    if player1_strategy == player2_strategy
      return player1
    end

    case player1_strategy
    when 'R'
      player2_strategy == 'S' ? player1 : player2
    when 'P'
      player2_strategy == 'R' ? player1 : player2
    when 'S'
      player2_strategy == 'P' ? player1 : player2
    end
  end

  def rps_tournament_winner(tournament)
    if tournament[0][0].is_a?(String)
      return rps_game_winner(tournament)
    end

    return rps_game_winner([rps_tournament_winner(tournament[0]), rps_tournament_winner(tournament[1])])
    # rps_game_winner([left_winner, right_winner])
  end

  class WrongNumberOfPlayersError < StandardError; end
  class NoSuchStrategyError < StandardError; end

end

app/helpers/anagrams_helper.rb
module AnagramsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/desserts_helper.rb
module DessertsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/palindrome_helper.rb
module PalindromeHelper
end

app/helpers/rock_paper_scissors_helper.rb
module RockPaperScissorsHelper
end

app/views/anagrams/check.html.erb
<h1>Find Anagrams</h1>

<%= form_with url: anagrams_check_path, method: :get, local: true do |f| %>
  <div class="form-group">
    <label for="words">Enter words (comma-separated):</label>
    <%= text_field_tag 'words', params[:words], class: 'form-control', 
        placeholder: 'Example: cars, racs, for, four, scar' %>
  </div>
  <%= submit_tag 'Find Anagrams', class: 'btn btn-primary' %>
<% end %>

<% if @result&.any? %>
  <h2>Anagram Groups Found:</h2>
  <ul>
    <% @result.each do |group| %>
      <li><%= group.join(', ') %></li>
    <% end %>
  </ul>
<% elsif @words&.any? %>
  <p>No anagrams found in the given words.</p>
<% end %>

app/views/desserts/index.html.erb
<h1>Dessert Checker</h1>

<div class="form-section">
  <%= form_tag(check_desserts_path, method: :post) do %>
    <div class="form-group">
      <%= label_tag :name, "Dessert Name:" %>
      <%= text_field_tag :name, nil, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= label_tag :calories, "Calories:" %>
      <%= number_field_tag :calories, nil, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= label_tag :flavor, "Flavor (for Jelly Beans only):" %>
      <%= text_field_tag :flavor, nil, class: 'form-control' %>
    </div>

    <%= submit_tag "Check Dessert", class: 'btn btn-primary' %>
  <% end %>
</div>

<h2>Example Desserts:</h2>
<ul>
  <li>
    Regular Dessert: <%= @dessert.name %> (<%= @dessert.calories %> calories)
    <br>
    Healthy? <%= @dessert.healthy? %>
    <br>
    Delicious? <%= @dessert.delicious? %>
  </li>

  <li>
    Healthy Dessert: <%= @healthy_dessert.name %> (<%= @healthy_dessert.calories %> calories)
    <br>
    Healthy? <%= @healthy_dessert.healthy? %>
    <br>
    Delicious? <%= @healthy_dessert.delicious? %>
  </li>

  <li>
    Cherry Jelly Bean: <%= @jelly_bean.name %> (<%= @jelly_bean.calories %> calories)
    <br>
    Flavor: <%= @jelly_bean.flavor %>
    <br>
    Healthy? <%= @jelly_bean.healthy? %>
    <br>
    Delicious? <%= @jelly_bean.delicious? %>
  </li>

  <li>
    Black Licorice Jelly Bean: <%= @black_licorice.name %> (<%= @black_licorice.calories %> calories)
    <br>
    Flavor: <%= @black_licorice.flavor %>
    <br>
    Healthy? <%= @black_licorice.healthy? %>
    <br>
    Delicious? <%= @black_licorice.delicious? %>
  </li>
</ul>

app/views/desserts/result.html.erb
<h1>Dessert Analysis</h1>

<div class="result-section">
  <h2><%= @dessert.name %></h2>
  <p>Calories: <%= @dessert.calories %></p>
  
  <% if @dessert.is_a?(JellyBean) %>
    <p>Flavor: <%= @dessert.flavor %></p>
  <% end %>
  
  <p>Is it healthy? <%= @dessert.healthy? ? "Yes" : "No" %></p>
  <p>Is it delicious? <%= @dessert.delicious? ? "Yes" : "No" %></p>
</div>

<%= link_to "Check Another Dessert", desserts_path, class: 'btn btn-primary' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Homework</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Welcom to exercises related to software engineering lecture </h1>
<%= button_to 'Check a Palindrome', palindrome_check_path, method: :get, class: 'btn btn-primary' %>
<br>
<%= button_to 'Play Rock-Paper-Scissors', rock_paper_scissors_check_path, method: :get, class: 'btn btn-primary' %>
<br>
<%= button_to 'Group Anagrams', anagrams_check_path, method: :get, class: 'btn btn-primary' %>
<br>
<%= button_to 'Dessert Checker', desserts_path, method: :get, class: 'btn btn-primary' %>
<br>

app/views/palindrome/check.html.erb
<h1>Palindrome Check</h1>
<form action="/palindrome/check" method="get">
    <label for="input">Enter a word or phrase:</label>
    <input type="text" id="input" name="input">
    <button type="submit">Check</button>
</form>

<% if @input %>
  <p><strong>Input:</strong> <%= @input %></p>
  <p><strong>Is Palindrome:</strong> <%= @result %></p>
<% end %>

app/views/rock_paper_scissors/check.html.erb
<h1>Rock-Paper-Scissors Game</h1>
<%= form_with url: '/rock_paper_scissors/check', method: :get do %>
  <div>
    <label for="player1_name">Player 1 Name:</label>
    <%= text_field_tag "input[0][name]", nil, id: "player1_name" %>
  </div>
  <div>
    <label for="player1_strategy">Player 1 Strategy (R/P/S):</label>
    <%= text_field_tag "input[0][strategy]", nil, id: "player1_strategy" %>
  </div>
  <div>
    <label for="player2_name">Player 2 Name:</label>
    <%= text_field_tag "input[1][name]", nil, id: "player2_name" %>
  </div>
  <div>
    <label for="player2_strategy">Player 2 Strategy (R/P/S):</label>
    <%= text_field_tag "input[1][strategy]", nil, id: "player2_strategy" %>
  </div>
  <%= submit_tag "Check Winner" %>
<% end %>

<% if @result %>
  <h2>Winner: <%= @result[0] %> (Strategy: <%= @result[1] %>)</h2>
<% end %>